# Generated by Django 5.2.5 on 2026-02-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_jobapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
